# Generated by Django 4.0.1 on 2022-02-14 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Corp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corp_no', models.CharField(max_length=10)),
                ('corp_nm', models.CharField(max_length=50)),
                ('ceo', models.CharField(max_length=10)),
                ('zipcode', models.CharField(blank=True, max_length=10)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('address2', models.CharField(blank=True, max_length=200)),
                ('telephone', models.CharField(blank=True, max_length=11)),
                ('cellphone', models.CharField(blank=True, max_length=11)),
                ('bank', models.CharField(blank=True, max_length=20)),
                ('account', models.CharField(blank=True, max_length=20)),
            ],
        ),
    ]
