# Generated by Django 4.0.1 on 2022-02-14 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_remove_codedt_code_id_codedt_code'),
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='biz_tp_cd',
        ),
        migrations.AddField(
            model_name='client',
            name='biz_tp_cd',
            field=models.ManyToManyField(null=True, related_name='biz_type', to='common.CodeDt'),
        ),
        migrations.RemoveField(
            model_name='client',
            name='client_tp_cd',
        ),
        migrations.AddField(
            model_name='client',
            name='client_tp_cd',
            field=models.ManyToManyField(null=True, related_name='client_type', to='common.CodeDt'),
        ),
    ]
