# Generated by Django 4.0.1 on 2022-02-14 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_nm', models.CharField(max_length=50)),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('unit_price', models.IntegerField(default=0)),
                ('comment', models.TextField(blank=True)),
            ],
        ),
    ]
