# Generated by Django 4.0.1 on 2022-02-14 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_ctg_cd',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
    ]
