# Generated by Django 4.0.1 on 2022-02-14 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_product_ctg_cd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_ctg_cd',
            field=models.CharField(max_length=10),
        ),
    ]
