# Generated by Django 4.0.1 on 2022-02-14 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_remove_codedt_code_id_codedt_code'),
        ('product', '0003_alter_product_product_ctg_cd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_ctg_cd',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.codedt'),
        ),
    ]
