# Generated by Django 4.0.1 on 2022-02-14 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_remove_codedt_code_id_codedt_code'),
        ('product', '0004_alter_product_product_ctg_cd'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_ctg_cd',
        ),
        migrations.AddField(
            model_name='product',
            name='product_ctgy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_product_ctgy', to='common.codedt'),
        ),
    ]
