# Generated by Django 4.0.1 on 2022-02-14 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_nm', models.CharField(max_length=100)),
                ('comment', models.TextField(blank=True)),
                ('depth', models.IntegerField(blank=True)),
                ('sort', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='CodeDt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_nm', models.CharField(max_length=100)),
                ('code_val', models.CharField(max_length=10)),
                ('comment', models.TextField(blank=True)),
                ('depth', models.IntegerField()),
                ('sort', models.IntegerField()),
                ('code_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='code_id', to='common.code')),
            ],
        ),
    ]
