# Generated by Django 4.0.1 on 2022-02-14 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codedt',
            name='code_id',
        ),
        migrations.AddField(
            model_name='codedt',
            name='code',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='code', to='common.code'),
            preserve_default=False,
        ),
    ]
