# Generated by Django 4.0.1 on 2022-02-14 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corp', '0001_initial'),
        ('acc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='user',
            name='address2',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='user',
            name='bank',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='birthday',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AddField(
            model_name='user',
            name='cellphone',
            field=models.CharField(blank=True, max_length=11),
        ),
        migrations.AddField(
            model_name='user',
            name='comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='corp_no',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.PROTECT, to='corp.corp'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='date_retired',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='license_plate_number',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='staff_tp_cd',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='user',
            name='telephone',
            field=models.CharField(blank=True, max_length=11),
        ),
        migrations.AddField(
            model_name='user',
            name='zipcode',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
