# Generated by Django 4.0.1 on 2022-02-14 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_remove_codedt_code_id_codedt_code'),
        ('acc', '0003_rename_corp_no_user_corp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='staff_tp_cd',
        ),
        migrations.AddField(
            model_name='user',
            name='staff_tp_cd',
            field=models.ManyToManyField(null=True, to='common.CodeDt'),
        ),
    ]
