# Generated by Django 4.0.1 on 2022-02-14 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_remove_codedt_code_id_codedt_code'),
        ('acc', '0006_remove_user_staff_tp_cd_alter_user_corp'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='staff_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_staff_type', to='common.codedt'),
        ),
    ]
