# Generated by Django 4.0.1 on 2022-02-14 10:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0002_remove_codedt_code_id_codedt_code'),
        ('product', '0003_alter_product_product_ctg_cd'),
        ('client', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(max_length=11)),
                ('orderdate', models.CharField(max_length=8)),
                ('unit', models.CharField(max_length=50)),
                ('unit_price', models.IntegerField()),
                ('quantity', models.IntegerField(default=1)),
                ('ammount', models.IntegerField()),
                ('approver', models.CharField(max_length=50)),
                ('comment', models.TextField(blank=True)),
                ('biz_tp_cd', models.ManyToManyField(related_name='biz_tp_cd', to='common.CodeDt')),
                ('client', models.ManyToManyField(to='client.Client')),
                ('payment_sts_cd', models.ManyToManyField(related_name='payment_sts_cd', to='common.CodeDt')),
                ('payment_tp_cd', models.ManyToManyField(related_name='payment_tp_cd', to='common.CodeDt')),
                ('product', models.ManyToManyField(to='product.Product')),
                ('staff', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
