# Generated by Django 4.0.1 on 2022-02-14 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='biz_tp_cd',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment_sts_cd',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment_tp_cd',
        ),
    ]
