# Generated by Django 4.0.1 on 2022-02-14 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_remove_codedt_code_id_codedt_code'),
        ('order', '0003_order_biz_tp_cd_order_payment_sts_cd_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_sts_cd',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_payment_sts_cd', to='common.codedt'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_tp_cd',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_payment_tp_cd', to='common.codedt'),
        ),
    ]
