# Generated by Django 4.0.1 on 2022-02-14 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_remove_codedt_code_id_codedt_code'),
        ('order', '0004_alter_order_payment_sts_cd_alter_order_payment_tp_cd'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='biz_tp_cd',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment_sts_cd',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment_tp_cd',
        ),
        migrations.AddField(
            model_name='order',
            name='biz_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='order_biz_type', to='common.codedt'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='payment_state',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='order_payment_state', to='common.codedt'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='payment_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='order_payment_type', to='common.codedt'),
            preserve_default=False,
        ),
    ]
