# Generated by Django 4.0.1 on 2022-02-15 06:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_remove_product_product_ctg_cd_product_product_ctgy'),
        ('client', '0006_remove_client_biz_tp_cd_remove_client_client_tp_cd_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0005_remove_order_biz_tp_cd_remove_order_payment_sts_cd_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='client',
        ),
        migrations.AddField(
            model_name='order',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='order_client', to='client.client'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='order_product', to='product.product'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='order',
            name='staff',
        ),
        migrations.AddField(
            model_name='order',
            name='staff',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='order_staff', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
