# Generated by Django 4.0.1 on 2022-02-16 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_remove_order_client_order_client_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='orderdate',
            field=models.CharField(max_length=10),
        ),
    ]
